### ISSUE TITLE
Delimited text

### ISSUE THREAD

**Issue by otofoto** [gacarrillor/loadthemall#23] opened 2020-07-06 10:39 UTC
How to change delimiter/separator when importing CSV files? Does it uses active regional settings?

**Comment by gacarrillor** [comment] 2020-07-13 02:21
CSV (customization) support will be added in future releases.

------------------
Note to self: https://github.com/qgis/QGIS/blob/a8de679601be931bd356a69f4b1cbb224581339d/src/providers/delimitedtext/qgsdelimitedtextsourceselect.cpp#L107-L219

**Comment by gacarrillor** [comment] 2021-12-21 15:28
Closing, as "customize loading of CSV files" is a duplicate of https://github.com/gacarrillor/loadthemall/issues/7

**Closed by gacarrillor** 2021-12-21 15:28 UTC
Labels: duplicate, Feature request
